### PR TITLE
adds file loading

### PR DESCRIPTION
**Pull request by justmat**
This is pretty bare-bones, so you'll likely want to test. A nice way to extend this feature would be to have the loop auto re-size to the loaded sample length, but I was trying to keep it simple and quick. :)

### CODE REVIEW

**Comment by justmat** [comment]
Please hold off on this one for just a bit. I think auto-resizing the loop to the file length might be easy.

edit: it is super easy, but requires a fix to ``audio.file_info()`` to work. Tehn said a fix is coming in a few days. So, why don't we wait until then to merge.

**Comment by oliviercreurer** [comment]
Sounds good (and sorry for the slow response)! Got another PR for arc support (!), so I'll likely bundle the two together once the `audio.file_info()` fix comes in. Not _too_ familiar with git, so hopefully I won't be looking at any kind of merge conflicts 😬

**Comment by justmat** [comment]
I went ahead and pulled in the fix for ``audio.file_info()`` and implemented the loop resizing bit, but am now running into some unexpected issues. The biggest thing being that file loading is far from instantaneous, and when softcut commands are being fired as well... things tend to get funky. Far too often resulting in a complete lock up that requires a restart. 

I'll keep poking at it, and hopefully a solution will be evident, though tbh... I am starting to wonder if this would be better suited for a sample focused spin off of compass. @oliviercreurer, any thoughts?

**Comment by oliviercreurer** [comment]
Dang - thanks for pulling in the fix, and for testing this so thoroughly @justmat . I agree with you that a spin-off app would likely be best, both to keep the current functionality smooth and to get you back to working on your own projects :) I wouldn't want this to suck up more of your time!

**Comment by justmat** [comment]
Haha, i'll probably work a spin off up at some point. Maybe I'll call it [sextant](https://en.wikipedia.org/wiki/Sextant) :D

**Pull request closed without merging**
